# Generated automatically by update.sh
# Do no edit this file

FROM bigtruedata/scala:<scala-version>

# Install build dependencies
RUN apk add --no-cache --virtual=.dependencies tar

RUN wget -O- "http://dl.bintray.com/sbt/native-packages/sbt/<sbt-version>/sbt-<sbt-version>.tgz" \\
    |  tar xzf - -C /usr/local --strip-components=1 \\
    && sbt exit

# Remove build dependencies
RUN apk del --no-cache .dependencies

VOLUME /app
WORKDIR /app

CMD ["sbt"]
