# Generated automatically by update.sh
# Do no edit this file

FROM bigtruedata/scala:<scala-version>

Run wget -O- "https://github.com/sbt/sbt/releases/download/v<sbt-version>/sbt-<sbt-version>.tgz" \
    |  tar xzf - -C /usr/local --strip-components=1 \
    && sbt exit

VOLUME /app
WORKDIR /app

CMD ["sbt"]
